
export enum AssetNames {
	Template = "template",
	InteractiveIntersection = "interactive-intersection",
	ClampUp = "clamps1",
	ClampRight = "clamps2",
	ClampDown = "clamps3",
	ClampLeft = "clamps4",

	CrossIntersection = "intersection1",
	TripleIntersectionUp = "intersection2",
	TripleIntersectionRight = "intersection3",
	TripleIntersectionDown = "intersection4",
	TripleIntersectionLeft = "intersection5",
	BendIntersectionUp = "intersection6",
	BendIntersectionRight = "intersection7",
	BendIntersectionDown = "intersection8",
	BendIntersectionLeft = "intersection9",
	BarIntersectionUp = "intersection10",
	BarIntersectionRight = "intersection11",
	SingleIntersectionUp = "intersection12",
	SingleIntersectionRight = "intersection13",
	SingleIntersectionDown = "intersection14",
	SingleIntersectionLeft = "intersection15",

	PipeHorizontalEmpty = "pipe-horizontal1",
	PipeHorizontalFull = "pipe-horizontal2",
	PipeVerticalEmpty = "pipe-vertical1",
	PipeVerticalFull = "pipe-vertical2",
}
