
export enum AssetNames {
	Template = "template",
	InteractiveIntersection = "interactive-intersection",
	ClampUp = "clamps1",
	ClampRight = "clamps2",
	ClampDown = "clamps3",
	ClampLeft = "clamps4",

	CrossIntersection = "intersection1",
	TripleIntersectionDown = "intersection2",
	TripleIntersectionLeft = "intersection3",
	TripleIntersectionUp = "intersection4",
	TripleIntersectionRight = "intersection5",
	BendIntersectionUp = "intersection6",
	BendIntersectionRight = "intersection7",
	BendIntersectionDown = "intersection8",
	BendIntersectionLeft = "intersection9",
	BarIntersectionUp = "intersection10",
	BarIntersectionRight = "intersection11",
	SingleIntersectionUp = "intersection12",
	SingleIntersectionRight = "intersection13",
	SingleIntersectionDown = "intersection14",
	SingleIntersectionLeft = "intersection15",

	PipeHorizontalEmpty = "pipe-horizontal1",
	PipeHorizontalFull = "pipe-horizontal2",
	PipeHorizontalAnimationFrame1 = "pipe-horizontal3",
	PipeHorizontalAnimationFrame2 = "pipe-horizontal4",
	PipeHorizontalAnimationFrame3 = "pipe-horizontal5",
	PipeVerticalEmpty = "pipe-vertical1",
	PipeVerticalFull = "pipe-vertical2",
	PipeVerticalAnimationFrame1 = "pipe-vertical3",
	PipeVerticalAnimationFrame2 = "pipe-vertical4",
	PipeVerticalAnimationFrame3 = "pipe-vertical5",

	Engine = "engines",
}
